wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1679998716.995603
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.7.11
      5: 0.14.0
      8:
      - 3
      - 5
